            waypointsList = {}
            table.insert(waypointsList, "CC Communications Check Point")
			table.insert(waypointsList, "LZ Landing Zone")
			table.insert(waypointsList, "PP Passage Point")
			table.insert(waypointsList, "RP Release Point")
			table.insert(waypointsList, "SP Start Point")
			table.insert(waypointsList, "WP Waypoint")

            hazardsList = {}
            table.insert(hazardsList, "TO Tower Over 1000’")
			table.insert(hazardsList, "TU Tower Under 1000’")
			table.insert(hazardsList, "WL Wires Power")
			table.insert(hazardsList, "WS Wires Telephone/Electric")

            controlMeasuresList = {}
            table.insert(controlMeasuresList, "AP Air Control Point")
			table.insert(controlMeasuresList, "AG Airfield General")
			table.insert(controlMeasuresList, "AI Airfield Instrument")
			table.insert(controlMeasuresList, "AL Lighted Airport")
			table.insert(controlMeasuresList, "F1 Artillery Firing Point 1")
			table.insert(controlMeasuresList, "F2 Artillery Firing Point 2")
			table.insert(controlMeasuresList, "AA Assembly Area")
			table.insert(controlMeasuresList, "BN Battalion")
			table.insert(controlMeasuresList, "BP Battle Position")
			table.insert(controlMeasuresList, "BR Bridge or Gap")
			table.insert(controlMeasuresList, "BD Brigade")
			table.insert(controlMeasuresList, "CP Checkpoint")
			table.insert(controlMeasuresList, "CO Company")
			table.insert(controlMeasuresList, "CR Corps")
			table.insert(controlMeasuresList, "DI Division")
			table.insert(controlMeasuresList, "FF FARP Fuel Only")
			table.insert(controlMeasuresList, "FM FARP Ammo Only")
			table.insert(controlMeasuresList, "FC FARP Fuel and Ammo")
			table.insert(controlMeasuresList, "FA Forward Assembly Area")
			table.insert(controlMeasuresList, "GL Ground Light/Small Town")
			table.insert(controlMeasuresList, "HA Holding Area")
			table.insert(controlMeasuresList, "NB NBC Area")
			table.insert(controlMeasuresList, "ID IDM Subscriber")
			table.insert(controlMeasuresList, "BE NDB Symbol")
			table.insert(controlMeasuresList, "RH Railhead Point")
			table.insert(controlMeasuresList, "GP Regiment or Group")
			table.insert(controlMeasuresList, "US US Army")
			table.insert(controlMeasuresList, "AD Friendly Air Defense")
			table.insert(controlMeasuresList, "AS Friendly Air Assault")
			table.insert(controlMeasuresList, "AV Friendly Air Cavalry")
			table.insert(controlMeasuresList, "AB Friendly Airborne")
			table.insert(controlMeasuresList, "AM Friendly Armor")
			table.insert(controlMeasuresList, "CA Friendly Armored Cavalry")
			table.insert(controlMeasuresList, "MA Friendly Aviation Maintenance")
			table.insert(controlMeasuresList, "CF Friendly Chemical")
			table.insert(controlMeasuresList, "DF Friendly Decontamination")
			table.insert(controlMeasuresList, "EN Friendly Engineers")
			table.insert(controlMeasuresList, "FW Friendly Electronic Warfare")
			table.insert(controlMeasuresList, "WF Friendly Fixed Wing")
			table.insert(controlMeasuresList, "FL Friendly Field Artillery")
			table.insert(controlMeasuresList, "AH Friendly Attack Helicopter")
			table.insert(controlMeasuresList, "FG Friendly Helicopter, General")
			table.insert(controlMeasuresList, "HO Friendly Hospital")
			table.insert(controlMeasuresList, "FI Friendly Infantry")
			table.insert(controlMeasuresList, "MI Friendly Mechanized Infantry")
			table.insert(controlMeasuresList, "MD Friendly Medical")
			table.insert(controlMeasuresList, "TF Friendly Tactical Operations Center")
			table.insert(controlMeasuresList, "FU Friendly Unit")
			table.insert(controlMeasuresList, "ES Enemy Air Assault")
			table.insert(controlMeasuresList, "EV Enemy Air Cavalry")
			table.insert(controlMeasuresList, "ED Enemy Air Defense")
			table.insert(controlMeasuresList, "EB Enemy Airborne")
			table.insert(controlMeasuresList, "EC Enemy Armored Cavalry")
			table.insert(controlMeasuresList, "AE Enemy Armor")
			table.insert(controlMeasuresList, "ME Enemy Aviation Maintenance")
			table.insert(controlMeasuresList, "CE Enemy Chemical")
			table.insert(controlMeasuresList, "DE Enemy Decontamination")
			table.insert(controlMeasuresList, "EE Enemy Engineers")
			table.insert(controlMeasuresList, "WR Enemy Electronic Warfare")
			table.insert(controlMeasuresList, "EF Enemy Field Artillery")
			table.insert(controlMeasuresList, "WE Enemy Fixed Wing")
			table.insert(controlMeasuresList, "EK Enemy Attack Helicopter")
			table.insert(controlMeasuresList, "HG Enemy Helicopter, General")
			table.insert(controlMeasuresList, "EH Enemy Hospital")
			table.insert(controlMeasuresList, "EI Enemy Infantry")
			table.insert(controlMeasuresList, "EM Enemy Mechanized Infantry")
			table.insert(controlMeasuresList, "EX Enemy Medical")
			table.insert(controlMeasuresList, "ET Enemy Tactical Operations Center")
			table.insert(controlMeasuresList, "EU Enemy Unit")

            targetList = {}
			table.insert(targetList, "TG Target Point")
            table.insert(targetList, "AX AMX-13 Air Defense Gun")
			table.insert(targetList, "AS Aspide SAM System")
			table.insert(targetList, "AD Friendly Air Defense Unit")
			table.insert(targetList, "GP Gepard Air Defense Gun")
			table.insert(targetList, "G1 Growth 1")
			table.insert(targetList, "G2 Growth 2")
			table.insert(targetList, "G3 Growth 3")
			table.insert(targetList, "G4 Growth 4")
			table.insert(targetList, "SD Spada SAM System")
			table.insert(targetList, "83 M1983 Air Defense Gun")
			table.insert(targetList, "U Unknown Air Defense Unit")
			table.insert(targetList, "S6 2S6 / SA-19 Air Defense Unit")
			table.insert(targetList, "AA Air Defense Gun")
			table.insert(targetList, "GU Generic Air Defense Unit")
			table.insert(targetList, "MK Marksman Air Defense Gun")
			table.insert(targetList, "SB Sabre Air Defense Gun")
			table.insert(targetList, "GS Self-Propelled Air Defense Gun")
			table.insert(targetList, "GT Towed Air Defense Gun")
			table.insert(targetList, "ZU ZSU-23-4 Air Defense Gun")
			table.insert(targetList, "NV Naval Air Defense System")
			table.insert(targetList, "SR Battlefield Surveillance Radar")
			table.insert(targetList, "TR Target Acquisition Radar")
			table.insert(targetList, "70 RBS-70 SAM System")
			table.insert(targetList, "BP Blowpipe SAM System")
			table.insert(targetList, "BH Bloodhound SAM System")
			table.insert(targetList, "CH Chapparal SAM System")
			table.insert(targetList, "CT Crotale SAM System")
			table.insert(targetList, "C2 CSA-2/1/X SAM System")
			table.insert(targetList, "HK Hawk SAM System")
			table.insert(targetList, "JA Javelin SAM System")
			table.insert(targetList, "PT Patriot SAM System")
			table.insert(targetList, "RE Redeye SAM System")
			table.insert(targetList, "RA Rapier SAM System")
			table.insert(targetList, "RO Roland SAM System")
			table.insert(targetList, "1 SA-1 SAM System")
			table.insert(targetList, "2 SA-2 SAM System")
			table.insert(targetList, "3 SA-3 SAM System")
			table.insert(targetList, "4 SA-4 SAM System")
			table.insert(targetList, "5 SA-5 SAM System")
			table.insert(targetList, "6 SA-6 SAM System")
			table.insert(targetList, "7 SA-7 SAM System")
			table.insert(targetList, "8 SA-8 SAM System")
			table.insert(targetList, "9 SA-9 SAM System")
			table.insert(targetList, "10 SA-10 SAM System")
			table.insert(targetList, "11 SA-11 SAM System")
			table.insert(targetList, "12 SA-12 SAM System")
			table.insert(targetList, "13 SA-13 SAM System")
			table.insert(targetList, "14 SA-14 SAM System")
			table.insert(targetList, "15 SA-15 SAM System")
			table.insert(targetList, "16 SA-16 SAM System")
			table.insert(targetList, "17 SA-17 SAM System")
			table.insert(targetList, "SM SAMP SAM System")
			table.insert(targetList, "SC SATCP SAM System")
			table.insert(targetList, "SP Self-Propelled SAM System")
			table.insert(targetList, "SH Shahine/R440 SAM System")
			table.insert(targetList, "SS Starstreak SAM System")
			table.insert(targetList, "TC Tigercat SAM System")
			table.insert(targetList, "ST Stinger SAM System")
			table.insert(targetList, "SA Towed SAM System")
			table.insert(targetList, "VU Vulcan Air Defense Gun")
            
            
            
            
            identList = {}
			table.insert(identList, "CC Communications Check Point")
			table.insert(identList, "LZ Landing Zone")
			table.insert(identList, "PP Passage Point")
			table.insert(identList, "RP Release Point")
			table.insert(identList, "SP Start Point")
			table.insert(identList, "WP Waypoint")
			table.insert(identList, "TO Tower Over 1000’")
			table.insert(identList, "TU Tower Under 1000’")
			table.insert(identList, "WL Wires Power")
			table.insert(identList, "WS Wires Telephone/Electric")

			table.insert(identList, "AP Air Control Point")
			table.insert(identList, "AG Airfield General")
			table.insert(identList, "AI Airfield Instrument")
			table.insert(identList, "AL Lighted Airport")
			table.insert(identList, "F1 Artillery Firing Point 1")
			table.insert(identList, "F2 Artillery Firing Point 2")
			table.insert(identList, "AA Assembly Area")
			table.insert(identList, "BN Battalion")
			table.insert(identList, "BP Battle Position")
			table.insert(identList, "BR Bridge or Gap")
			table.insert(identList, "BD Brigade")
			table.insert(identList, "CP Checkpoint")
			table.insert(identList, "CO Company")
			table.insert(identList, "CR Corps")
			table.insert(identList, "DI Division")
			table.insert(identList, "FF FARP Fuel Only")
			table.insert(identList, "FM FARP Ammo Only")
			table.insert(identList, "FC FARP Fuel and Ammo")
			table.insert(identList, "FA Forward Assembly Area")
			table.insert(identList, "GL Ground Light/Small Town")
			table.insert(identList, "HA Holding Area")
			table.insert(identList, "NB NBC Area")
			table.insert(identList, "ID IDM Subscriber")
			table.insert(identList, "BE NDB Symbol")
			table.insert(identList, "RH Railhead Point")
			table.insert(identList, "GP Regiment or Group")
			table.insert(identList, "US US Army")
			table.insert(identList, "AD Friendly Air Defense")
			table.insert(identList, "AS Friendly Air Assault")
			table.insert(identList, "AV Friendly Air Cavalry")
			table.insert(identList, "AB Friendly Airborne")
			table.insert(identList, "AM Friendly Armor")
			table.insert(identList, "CA Friendly Armored Cavalry")
			table.insert(identList, "MA Friendly Aviation Maintenance")
			table.insert(identList, "CF Friendly Chemical")
			table.insert(identList, "DF Friendly Decontamination")
			table.insert(identList, "EN Friendly Engineers")
			table.insert(identList, "FW Friendly Electronic Warfare")
			table.insert(identList, "WF Friendly Fixed Wing")
			table.insert(identList, "FL Friendly Field Artillery")
			table.insert(identList, "AH Friendly Attack Helicopter")
			table.insert(identList, "FG Friendly Helicopter, General")
			table.insert(identList, "HO Friendly Hospital")
			table.insert(identList, "FI Friendly Infantry")
			table.insert(identList, "MI Friendly Mechanized Infantry")
			table.insert(identList, "MD Friendly Medical")
			table.insert(identList, "TF Friendly Tactical Operations Center")
			table.insert(identList, "FU Friendly Unit")
			table.insert(identList, "ES Enemy Air Assault")
			table.insert(identList, "EV Enemy Air Cavalry")
			table.insert(identList, "ED Enemy Air Defense")
			table.insert(identList, "EB Enemy Airborne")
			table.insert(identList, "EC Enemy Armored Cavalry")
			table.insert(identList, "AE Enemy Armor")
			table.insert(identList, "ME Enemy Aviation Maintenance")
			table.insert(identList, "CE Enemy Chemical")
			table.insert(identList, "DE Enemy Decontamination")
			table.insert(identList, "EE Enemy Engineers")
			table.insert(identList, "WR Enemy Electronic Warfare")
			table.insert(identList, "EF Enemy Field Artillery")
			table.insert(identList, "WE Enemy Fixed Wing")
			table.insert(identList, "EK Enemy Attack Helicopter")
			table.insert(identList, "HG Enemy Helicopter, General")
			table.insert(identList, "EH Enemy Hospital")
			table.insert(identList, "EI Enemy Infantry")
			table.insert(identList, "EM Enemy Mechanized Infantry")
			table.insert(identList, "EX Enemy Medical")
			table.insert(identList, "ET Enemy Tactical Operations Center")
			table.insert(identList, "EU Enemy Unit")
			table.insert(identList, "TG Target Point")

			table.insert(identList, "AX AMX-13 Air Defense Gun")
			table.insert(identList, "AS Aspide SAM System")
			table.insert(identList, "AD Friendly Air Defense Unit")
			table.insert(identList, "GP Gepard Air Defense Gun")
			table.insert(identList, "G1 Growth 1")
			table.insert(identList, "G2 Growth 2")
			table.insert(identList, "G3 Growth 3")
			table.insert(identList, "G4 Growth 4")
			table.insert(identList, "SD Spada SAM System")
			table.insert(identList, "83 M1983 Air Defense Gun")
			table.insert(identList, "U Unknown Air Defense Unit")
			table.insert(identList, "S6 2S6 / SA-19 Air Defense Unit")
			table.insert(identList, "AA Air Defense Gun")
			table.insert(identList, "GU Generic Air Defense Unit")
			table.insert(identList, "MK Marksman Air Defense Gun")
			table.insert(identList, "SB Sabre Air Defense Gun")
			table.insert(identList, "GS Self-Propelled Air Defense Gun")
			table.insert(identList, "GT Towed Air Defense Gun")
			table.insert(identList, "ZU ZSU-23-4 Air Defense Gun")
			table.insert(identList, "NV Naval Air Defense System")
			table.insert(identList, "SR Battlefield Surveillance Radar")
			table.insert(identList, "TR Target Acquisition Radar")
			table.insert(identList, "70 RBS-70 SAM System")
			table.insert(identList, "BP Blowpipe SAM System")
			table.insert(identList, "BH Bloodhound SAM System")
			table.insert(identList, "CH Chapparal SAM System")
			table.insert(identList, "CT Crotale SAM System")
			table.insert(identList, "C2 CSA-2/1/X SAM System")
			table.insert(identList, "HK Hawk SAM System")
			table.insert(identList, "JA Javelin SAM System")
			table.insert(identList, "PT Patriot SAM System")
			table.insert(identList, "RE Redeye SAM System")
			table.insert(identList, "RA Rapier SAM System")
			table.insert(identList, "RO Roland SAM System")
			table.insert(identList, "1 SA-1 SAM System")
			table.insert(identList, "2 SA-2 SAM System")
			table.insert(identList, "3 SA-3 SAM System")
			table.insert(identList, "4 SA-4 SAM System")
			table.insert(identList, "5 SA-5 SAM System")
			table.insert(identList, "6 SA-6 SAM System")
			table.insert(identList, "7 SA-7 SAM System")
			table.insert(identList, "8 SA-8 SAM System")
			table.insert(identList, "9 SA-9 SAM System")
			table.insert(identList, "10 SA-10 SAM System")
			table.insert(identList, "11 SA-11 SAM System")
			table.insert(identList, "12 SA-12 SAM System")
			table.insert(identList, "13 SA-13 SAM System")
			table.insert(identList, "14 SA-14 SAM System")
			table.insert(identList, "15 SA-15 SAM System")
			table.insert(identList, "16 SA-16 SAM System")
			table.insert(identList, "17 SA-17 SAM System")
			table.insert(identList, "SM SAMP SAM System")
			table.insert(identList, "SC SATCP SAM System")
			table.insert(identList, "SP Self-Propelled SAM System")
			table.insert(identList, "SH Shahine/R440 SAM System")
			table.insert(identList, "SS Starstreak SAM System")
			table.insert(identList, "TC Tigercat SAM System")
			table.insert(identList, "ST Stinger SAM System")
			table.insert(identList, "SA Towed SAM System")
			table.insert(identList, "VU Vulcan Air Defense Gun")